site_name: "PHongo: The MongoDB Driver for PHP"
repo_url: https://github.com/mongodb-labs/mongo-php-driver-prototype
theme: spacelab
pages:
    - [index.md, Home]
    - [crud.md, "CRUD", "Basic"]
    - [bulk.md, "CRUD", "Bulks"]
    - [commands.md, Commands]
    - [ods.md, Object Document Serialization]
extra_javascript:
    - pretty.js
    - jira.js
