site_name: "PHongo: The MongoDB Driver for PHP"
repo_url: https://github.com/bjori/phongo
theme: spacelab
pages:
    - [index.md, Home]
    - [crud.md, "CRUD", "Basic"]
    - [batch.md, "CRUD", "Batches"]
    - [commands.md, Commands]
extra_javascript:
    - pretty.js
