site_name: "PHongo: The MongoDB Driver for PHP"
site_dir: ../phongo-website/
repo_url: https://github.com/10gen-labs/mongo-php-driver-prototype
theme: spacelab
pages:
    - [index.md, Home]
    - [crud.md, "CRUD", "Basic"]
    - [batch.md, "CRUD", "Batches"]
    - [commands.md, Commands]
extra_javascript:
    - pretty.js
    - jira.js
